apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    {{- include "instavote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: http
      nodePort: {{ .Values.vote.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "instavote.selectorLabels" . | nindent 4 }}
